# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31a48f3f8705006fd6b2cb638e86d39f9051e061a9b74c8591390c79c0a1a3d20da1f7e3f742a19464e9424899b3d4906eba3babdbf94eec1a5245eaa01270ec

test:
  secret_key_base: bc6483477370ee7e25b059794322ac964ceb928f30f183b10f548b931fe223d87a993861c1329007fb7df4de2b2d0dea0298be8fcfa9fab69202daa88d65f512

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
